[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [{ name = "typescript-language-server", except-features = [ "format" ] }, { name = "biome", only-features = [ "format" ] }]
auto-format = true

[[language]]
name = "typescript"
language-servers = [{ name = "typescript-language-server", except-features = [ "format" ] }, { name = "biome", only-features = [ "format" ] }]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [{ name = "typescript-language-server", except-features = [ "format" ] }, { name = "biome", only-features = [ "format" ] }]

[[language]]
name = "jsx"
language-servers = [{ name = "typescript-language-server", except-features = [ "format" ] }, { name = "biome", only-features = [ "format" ] }]
auto-format = true

[[language]]
name = "json"
language-servers = ["biome"]
auto-format = true
